apiVersion: v1
kind: ConfigMap
metadata:
  name: customers-service
  namespace: petclinic-dev
  labels:
    app.kubernetes.io/name: customers-service
    app.kubernetes.io/part-of: petclinic
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: service
data:
  SPRING_PROFILES_ACTIVE: "docker,mysql"
  CONFIG_SERVER_URL: "http://config-server:8888"
  # Prod overlay must patch this value with the prod RDS endpoint
  SPRING_DATASOURCE_URL: "jdbc:mysql://petclinic-dev-mysql.ctsqcf8pctvr.us-east-1.rds.amazonaws.com:3306/petclinic"
