apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: customers-service-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/rajdev0ps/petclinic-platform.git"
    targetRevision: main
    path: helm/petclinic-service
    helm:
      releaseName: customers-service
      valueFiles:
        - ../../helm-values/customers-service.yaml
        - ../../helm-values/prod.yaml
      parameters:
        - name: image.registry
          value: "995679261046.dkr.ecr.us-east-1.amazonaws.com/petclinic-prod"
        - name: configMap.data.SPRING_DATASOURCE_URL
          value: "RDS_JDBC_URL_PROD"
  destination:
    server: https://kubernetes.default.svc
    namespace: petclinic-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
