apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: genai-service-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/rajdev0ps/petclinic-platform.git"
    targetRevision: main
    path: helm/petclinic-service
    helm:
      releaseName: genai-service
      valueFiles:
        - ../../helm-values/genai-service.yaml
        - ../../helm-values/prod.yaml
      parameters:
        - name: image.registry
          value: "995679261046.dkr.ecr.us-east-1.amazonaws.com/petclinic-prod"
  destination:
    server: https://kubernetes.default.svc
    namespace: petclinic-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
