apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: genai-service-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "PLATFORM_REPO_URL"
    targetRevision: main
    path: helm/petclinic-service
    helm:
      releaseName: genai-service
      valueFiles:
        - ../../helm-values/genai-service.yaml
        - ../../helm-values/prod.yaml
      parameters:
        - name: image.registry
          value: "ECR_REGISTRY_PROD"
  destination:
    server: https://kubernetes.default.svc
    namespace: petclinic-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
