locals {
  name_prefix   = "${var.project}-${var.environment}"
  db_identifier = "${local.name_prefix}-mysql"
}

# ─── Random Password ──────────────────────────────────────────────────────────
# Excludes / @ " ' ` which cause issues in MySQL connection strings

resource "random_password" "rds" {
  length           = 16
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

# ─── Customer-Managed KMS Key for RDS Credentials Secret ─────────────────────
# Separate CMK from the secrets module key so RDS credentials can be rotated/revoked
# independently. Key rotation enabled; prod uses 30-day deletion window.

resource "aws_kms_key" "rds_secrets" {
  description             = "CMK for RDS credentials secret in ${local.name_prefix}"
  deletion_window_in_days = var.skip_final_snapshot ? 7 : 30
  enable_key_rotation     = true

  tags = merge(var.tags, {
    Name = "${local.name_prefix}-rds-secrets-key"
  })
}

resource "aws_kms_alias" "rds_secrets" {
  name          = "alias/${local.name_prefix}-rds-secrets"
  target_key_id = aws_kms_key.rds_secrets.key_id
}

# ─── Secrets Manager — RDS Credentials (PETPLAT-23) ─────────────────────────
# Single JSON secret: {"username":"petclinic","password":"<generated>"}
# Secret name follows the forward-slash convention: petclinic/{env}/rds-credentials

resource "aws_secretsmanager_secret" "rds_credentials" {
  name        = "petclinic/${var.environment}/rds-credentials"
  description = "RDS MySQL master credentials for ${local.name_prefix}"
  kms_key_id  = aws_kms_key.rds_secrets.arn

  # 0 = immediate deletion in dev (allows re-creation after destroy with the same name).
  # 30 = recovery window in prod (matches skip_final_snapshot = false posture).
  recovery_window_in_days = var.skip_final_snapshot ? 0 : 30

  tags = merge(var.tags, {
    Name    = "${local.name_prefix}-rds-credentials"
    Service = "rds"
  })
}

resource "aws_secretsmanager_secret_version" "rds_credentials" {
  secret_id = aws_secretsmanager_secret.rds_credentials.id
  secret_string = jsonencode({
    username = "petclinic"
    password = random_password.rds.result
  })
}

# ─── DB Subnet Group ─────────────────────────────────────────────────────────

resource "aws_db_subnet_group" "main" {
  name        = "${local.name_prefix}-db-subnet-group"
  description = "DB subnet group for ${local.name_prefix} RDS instance"
  subnet_ids  = var.subnet_ids

  tags = merge(var.tags, {
    Name = "${local.name_prefix}-db-subnet-group"
  })
}

# ─── DB Parameter Group ──────────────────────────────────────────────────────
# utf8mb4 is required for full Unicode support (emoji, multi-byte CJK characters)

resource "aws_db_parameter_group" "mysql8" {
  name        = "${local.name_prefix}-mysql8"
  family      = "mysql8.0"
  description = "MySQL 8.0 parameters for ${local.name_prefix}"

  parameter {
    name  = "character_set_server"
    value = "utf8mb4"
  }

  parameter {
    name  = "collation_server"
    value = "utf8mb4_unicode_ci"
  }

  tags = merge(var.tags, {
    Name = "${local.name_prefix}-mysql8"
  })

  lifecycle {
    create_before_destroy = true
  }
}

# ─── RDS Instance ─────────────────────────────────────────────────────────────
# Single shared `petclinic` database for all 3 domain services (customers, visits, vets).
# Confirmed shared design by cross-service FK: visits.pet_id → pets.id (owned by customers).

resource "aws_db_instance" "main" {
  identifier = local.db_identifier

  engine         = "mysql"
  engine_version = "8.0"
  instance_class = var.instance_class

  # Storage — gp3 is free-tier eligible and cheaper than gp2 with better baseline IOPS
  allocated_storage     = var.allocated_storage
  max_allocated_storage = var.max_allocated_storage
  storage_type          = "gp3"
  storage_encrypted     = true

  # Credentials — generated by random_password, stored in Secrets Manager above
  db_name  = "petclinic"
  username = "petclinic"
  password = random_password.rds.result

  # Network — placed in VPC subnets, accessible only via RDS security group (port 3306 from EKS nodes)
  db_subnet_group_name   = aws_db_subnet_group.main.name
  vpc_security_group_ids = [var.security_group_id]
  publicly_accessible    = false

  parameter_group_name = aws_db_parameter_group.mysql8.name

  # HA — false for both envs (cost optimization; students learn when to enable Multi-AZ)
  multi_az = var.multi_az

  # Backup
  backup_retention_period    = var.backup_retention_period
  backup_window              = "03:00-04:00"
  maintenance_window         = "Mon:04:00-Mon:05:00"
  auto_minor_version_upgrade = false

  # Lifecycle
  skip_final_snapshot       = var.skip_final_snapshot
  final_snapshot_identifier = var.skip_final_snapshot ? null : "${local.db_identifier}-final-snapshot"
  deletion_protection       = var.deletion_protection

  tags = merge(var.tags, {
    Name = local.db_identifier
  })

  lifecycle {
    precondition {
      condition     = var.max_allocated_storage >= var.allocated_storage
      error_message = "max_allocated_storage (${var.max_allocated_storage}) must be >= allocated_storage (${var.allocated_storage})."
    }
  }
}
