apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-server-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "PLATFORM_REPO_URL"
    targetRevision: main
    path: helm/petclinic-service
    helm:
      releaseName: config-server
      valueFiles:
        - ../../helm-values/config-server.yaml
        - ../../helm-values/dev.yaml
      parameters:
        - name: image.registry
          value: "ECR_REGISTRY_DEV"
  destination:
    server: https://kubernetes.default.svc
    namespace: petclinic-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
