apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: customers-service-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/rajdev0ps/petclinic-platform.git"
    targetRevision: main
    path: helm/petclinic-service
    helm:
      releaseName: customers-service
      valueFiles:
        - ../../helm-values/customers-service.yaml
        - ../../helm-values/dev.yaml
      parameters:
        - name: image.registry
          value: "995679261046.dkr.ecr.us-east-1.amazonaws.com/petclinic-dev"
        - name: configMap.data.SPRING_DATASOURCE_URL
          value: "jdbc:mysql://petclinic-dev-mysql.ca98wu4yw5gu.us-east-1.rds.amazonaws.com:3306/petclinic"
  destination:
    server: https://kubernetes.default.svc
    namespace: petclinic-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
